# Site settings
title: A blog about Graduate School
description: Posting ground for my projects and musings within grad school (and hopefully beyond!)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Scott Kulm
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Graduate Student
email: scott.kulm@gmail.com
twitter_username: KulmScott
github_username:  kulmsc
gplus_username:  scott-kulm

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
