# Site settings
title: A blog about Graduate School
description: Posting ground for my projects and musings within grad school (and hopefully beyond!)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Scott Kulm
user_description: Current Graduate Student at Weill Cornell Medicine, coadvised by Drs. Elemento and Mezey.  Researching polygenic risk scores, and in particular how pleiotropy can be leveraged to improve disease prediction.  I like to live at the cross roads of coding, statistics, biology and creative thought.  Former chemical engineering student at The Cooper Union, stil a son and brother.
user_title: Graduate Student
email: scott.kulm@gmail.com
twitter_username: KulmScott
github_username:  kulmsc
gplus_username:  scott-kulm

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
